name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: MonitorSwitcher\MonitorSwitcher.csproj     # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish -r win-x64 /p:PublishSingleFile=true --self-contained MonitorSwitcher\MonitorSwitcher.csproj
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MonitorSwitcher
        path: MonitorSwitcher\bin\Debug\net6.0\win-x64\publish\MonitorSwitcher.exe
    - name: Upload powershell
      uses: actions/upload-artifact@v2
      with:
        name: MonitorSwitcher
        path: SimplePowerShellMenu\*.ps1